// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package networkconnectivity_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccNetworkConnectivityGatewayAdvertisedRoute_networkConnectivityGatewayAdvertisedRouteBasicExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckNetworkConnectivityGatewayAdvertisedRouteDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccNetworkConnectivityGatewayAdvertisedRoute_networkConnectivityGatewayAdvertisedRouteBasicExample(context),
			},
			{
				ResourceName:            "google_network_connectivity_gateway_advertised_route.default",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"labels", "location", "spoke", "terraform_labels"},
			},
			{
				ResourceName:       "google_network_connectivity_gateway_advertised_route.default",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccNetworkConnectivityGatewayAdvertisedRoute_networkConnectivityGatewayAdvertisedRouteBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_network" "network" {
  provider = google-beta
  name        = "tf-test-net-spoke%{random_suffix}"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "subnetwork" {
  provider = google-beta
  name          = "tf-test-subnet%{random_suffix}"
  ip_cidr_range = "10.0.0.0/28"
  region        = "us-central1"
  network       = google_compute_network.network.self_link
}

resource "google_network_connectivity_hub" "basic_hub" {
  provider = google-beta
  name        = "hub%{random_suffix}"
  description = "A sample hub"
  labels = {
    label-two = "value-one"
  }
  preset_topology = "HYBRID_INSPECTION"
}

resource "google_network_connectivity_spoke" "primary" {
  provider = google-beta
  name        = "tf-test-spoke-name%{random_suffix}"
  location = "us-central1"
  description = "A sample spoke of type Gateway"
  labels = {
    label-one = "value-one"
  }
  hub =  google_network_connectivity_hub.basic_hub.id
  gateway {
    ip_range_reservations {
      ip_range = "10.0.0.0/23"
    }
    capacity = "CAPACITY_1_GBPS"
  }
  group = "gateways"
}

resource "google_network_connectivity_gateway_advertised_route" "default" {
  provider      = google-beta
  spoke         = google_network_connectivity_spoke.primary.name
  location      = "us-central1"
  name          = "tf-test-gateway-advertised-route-name%{random_suffix}"
  labels = {
    label-one = "value-one"
  }
  description   = "description of the gateway advertised route"
  ip_range      = "0.0.0.0/24"
  recipient     = "ADVERTISE_TO_HUB"
  priority      = 200
}
`, context)
}

func testAccCheckNetworkConnectivityGatewayAdvertisedRouteDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_network_connectivity_gateway_advertised_route" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{NetworkConnectivityBasePath}}projects/{{project}}/locations/{{location}}/spokes/{{spoke}}/gatewayAdvertisedRoutes/{{name}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("NetworkConnectivityGatewayAdvertisedRoute still exists at %s", url)
			}
		}

		return nil
	}
}
