// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/compute/BackendBucket.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples/base_configs/iam_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
)

var (
	_ = fmt.Sprintf
	_ = strings.Trim
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
)

func TestAccComputeBackendBucketIamBindingGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeBackendBucketIamBinding_basicGenerated(context),
			},
			{
				ResourceName:      "google_compute_backend_bucket_iam_binding.foo",
				ImportStateIdFunc: generateComputeBackendBucketIAMBindingStateID("google_compute_backend_bucket_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				// Test Iam Binding update
				Config: testAccComputeBackendBucketIamBinding_updateGenerated(context),
			},
			{
				ResourceName:      "google_compute_backend_bucket_iam_binding.foo",
				ImportStateIdFunc: generateComputeBackendBucketIAMBindingStateID("google_compute_backend_bucket_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccComputeBackendBucketIamMemberGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				// Test Iam Member creation (no update for member, no need to test)
				Config: testAccComputeBackendBucketIamMember_basicGenerated(context),
			},
			{
				ResourceName:      "google_compute_backend_bucket_iam_member.foo",
				ImportStateIdFunc: generateComputeBackendBucketIAMMemberStateID("google_compute_backend_bucket_iam_member.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccComputeBackendBucketIamPolicyGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeBackendBucketIamPolicy_basicGenerated(context),
				Check:  resource.TestCheckResourceAttrSet("data.google_compute_backend_bucket_iam_policy.foo", "policy_data"),
			},
			{
				ResourceName:      "google_compute_backend_bucket_iam_policy.foo",
				ImportStateIdFunc: generateComputeBackendBucketIAMPolicyStateID("google_compute_backend_bucket_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccComputeBackendBucketIamPolicy_emptyBinding(context),
			},
			{
				ResourceName:      "google_compute_backend_bucket_iam_policy.foo",
				ImportStateIdFunc: generateComputeBackendBucketIAMPolicyStateID("google_compute_backend_bucket_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccComputeBackendBucketIamMember_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_backend_bucket" "image_backend" {
  name        = "tf-test-image-backend-bucket%{random_suffix}"
  description = "Contains beautiful images"
  bucket_name = google_storage_bucket.image_bucket.name
  enable_cdn  = true
}

resource "google_storage_bucket" "image_bucket" {
  name     = "tf-test-image-store-bucket%{random_suffix}"
  location = "EU"
}

resource "google_compute_backend_bucket_iam_member" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
}
`, context)
}

func testAccComputeBackendBucketIamPolicy_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_backend_bucket" "image_backend" {
  name        = "tf-test-image-backend-bucket%{random_suffix}"
  description = "Contains beautiful images"
  bucket_name = google_storage_bucket.image_bucket.name
  enable_cdn  = true
}

resource "google_storage_bucket" "image_bucket" {
  name     = "tf-test-image-store-bucket%{random_suffix}"
  location = "EU"
}

data "google_iam_policy" "foo" {
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
  }
}

resource "google_compute_backend_bucket_iam_policy" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  policy_data = data.google_iam_policy.foo.policy_data
}

data "google_compute_backend_bucket_iam_policy" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  depends_on = [
    google_compute_backend_bucket_iam_policy.foo
  ]
}
`, context)
}

func testAccComputeBackendBucketIamPolicy_emptyBinding(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_backend_bucket" "image_backend" {
  name        = "tf-test-image-backend-bucket%{random_suffix}"
  description = "Contains beautiful images"
  bucket_name = google_storage_bucket.image_bucket.name
  enable_cdn  = true
}

resource "google_storage_bucket" "image_bucket" {
  name     = "tf-test-image-store-bucket%{random_suffix}"
  location = "EU"
}

data "google_iam_policy" "foo" {
}

resource "google_compute_backend_bucket_iam_policy" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  policy_data = data.google_iam_policy.foo.policy_data
}
`, context)
}

func testAccComputeBackendBucketIamBinding_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_backend_bucket" "image_backend" {
  name        = "tf-test-image-backend-bucket%{random_suffix}"
  description = "Contains beautiful images"
  bucket_name = google_storage_bucket.image_bucket.name
  enable_cdn  = true
}

resource "google_storage_bucket" "image_bucket" {
  name     = "tf-test-image-store-bucket%{random_suffix}"
  location = "EU"
}

resource "google_compute_backend_bucket_iam_binding" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
}
`, context)
}

func testAccComputeBackendBucketIamBinding_updateGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_backend_bucket" "image_backend" {
  name        = "tf-test-image-backend-bucket%{random_suffix}"
  description = "Contains beautiful images"
  bucket_name = google_storage_bucket.image_bucket.name
  enable_cdn  = true
}

resource "google_storage_bucket" "image_bucket" {
  name     = "tf-test-image-store-bucket%{random_suffix}"
  location = "EU"
}

resource "google_compute_backend_bucket_iam_binding" "foo" {
  project = google_compute_backend_bucket.image_backend.project
  name = google_compute_backend_bucket.image_backend.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com", "user:gterraformtest1@gmail.com"]
}
`, context)
}

func generateComputeBackendBucketIAMPolicyStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		name := tpgresource.GetResourceNameFromSelfLink(rawState["name"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/global/backendBuckets/%s", project, name), "", "", rawState["condition.0.title"]), nil
	}
}

func generateComputeBackendBucketIAMBindingStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		name := tpgresource.GetResourceNameFromSelfLink(rawState["name"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/global/backendBuckets/%s", project, name), rawState["role"], "", rawState["condition.0.title"]), nil
	}
}

func generateComputeBackendBucketIAMMemberStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		project := tpgresource.GetResourceNameFromSelfLink(rawState["project"])
		name := tpgresource.GetResourceNameFromSelfLink(rawState["name"])
		return acctest.BuildIAMImportId(fmt.Sprintf("projects/%s/global/backendBuckets/%s", project, name), rawState["role"], rawState["member"], rawState["condition.0.title"]), nil
	}
}
