// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package compute_test

import (
	"fmt"
	"log"
	"regexp"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/services/compute"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = regexp.MatchString
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
	_ = compute.Product
)

func TestAccComputeRegionNetworkPolicyTrafficClassificationRule_regionNetworkPolicyTrafficClassificationRuleBasicExample(t *testing.T) {
	t.Parallel()

	randomSuffix := acctest.RandString(t, 10)

	context := map[string]interface{}{
		"project_name":  envvar.GetTestProjectFromEnv(),
		"region":        envvar.GetTestRegionFromEnv(),
		"nw_policy":     "tf-test-nw-policy" + randomSuffix,
		"random_suffix": randomSuffix,
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckComputeRegionNetworkPolicyTrafficClassificationRuleDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccComputeRegionNetworkPolicyTrafficClassificationRule_regionNetworkPolicyTrafficClassificationRuleBasicExample(context),
			},
			{
				ResourceName:            "google_compute_region_network_policy_traffic_classification_rule.primary",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"network_policy", "region"},
			},
			{
				ResourceName:       "google_compute_region_network_policy_traffic_classification_rule.primary",
				RefreshState:       true,
				ExpectNonEmptyPlan: true,
				ImportStateKind:    resource.ImportBlockWithResourceIdentity,
			},
		},
	})
}

func testAccComputeRegionNetworkPolicyTrafficClassificationRule_regionNetworkPolicyTrafficClassificationRuleBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_compute_region_network_policy" "basic_regional_network_policy" {
  provider     = google-beta

  name        = "%{nw_policy}"
  description = "Sample regional network firewall policy"
  project     = "%{project_name}"
  region      = "%{region}"
}

resource "google_compute_region_network_policy_traffic_classification_rule" "primary" {
  provider     = google-beta

  rule_name               = "test-rule"
  description             = "This is a simple rule description"
  disabled                = false
  network_policy          = google_compute_region_network_policy.basic_regional_network_policy.name
  priority                = 1000
  region                  = "%{region}"

  action {
    traffic_class = "TC1"
    dscp_mode = "AUTO"
  }
  match {
    src_ip_ranges            = ["10.100.0.1/32"]
    dest_ip_ranges           = ["11.100.0.1/32"]
    layer4_configs {
      ip_protocol = "all"
    }
  }
}
`, context)
}

func testAccCheckComputeRegionNetworkPolicyTrafficClassificationRuleDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_compute_region_network_policy_traffic_classification_rule" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)
			url, err := tpgresource.ReplaceVarsForTest(config, rs, transport_tpg.BaseUrl(compute.Product, config)+"projects/{{project}}/regions/{{region}}/networkPolicies/{{network_policy}}/getTrafficClassificationRule?priority={{priority}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("ComputeRegionNetworkPolicyTrafficClassificationRule still exists at %s", url)
			}
		}

		return nil
	}
}
