// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0
// ----------------------------------------------------------------------------
//
//	***     AUTO GENERATED CODE    ***    Type: Handwritten     ***
//
// ----------------------------------------------------------------------------
//
//	This code is generated by Magic Modules using the following:
//
//	Source file: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/third_party/terraform/services/firebase/client.go.tmpl
//
//	DO NOT EDIT this file directly. Any changes made to this file will be
//	overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------
package firebase

import (
	"context"
	"log"
	"strings"

	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
	firebase "google.golang.org/api/firebase/v1beta1"
	"google.golang.org/api/option"
)

func NewClient(ctx context.Context, c *transport_tpg.Config, userAgent string) *firebase.Service {
	firebaseClientBasePath := transport_tpg.RemoveBasePathVersion(c.FirebaseBasePath)
	firebaseClientBasePath = strings.ReplaceAll(firebaseClientBasePath, "/firebase/", "")
	log.Printf("[INFO] Instantiating Google Cloud firebase client for path %s", firebaseClientBasePath)
	clientFirebase, err := firebase.NewService(c.Context, option.WithHTTPClient(c.Client))
	if err != nil {
		log.Printf("[WARN] Error creating client firebase: %s", err)
		return nil
	}
	clientFirebase.UserAgent = userAgent
	clientFirebase.BasePath = firebaseClientBasePath

	return clientFirebase
}
