# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_os_config_guest_policies'
generation_type: 'mmv1'
source_file: 'products/osconfig/GuestPolicies.yaml'
api_service_name: 'osconfig.googleapis.com'
api_version: 'v1beta'
api_resource_type_kind: 'GuestPolicy'
api_variant_patterns:
  - 'folders/{folder}/guestPolicies/{guestPolicy}'
  - 'organizations/{organization}/guestPolicies/{guestPolicy}'
  - 'projects/{project}/guestPolicies/{guestPolicy}'
fields:
  - field: 'assignment.group_labels.labels'
  - field: 'assignment.instance_name_prefixes'
  - field: 'assignment.instances'
  - field: 'assignment.os_types.os_architecture'
  - field: 'assignment.os_types.os_short_name'
  - field: 'assignment.os_types.os_version'
  - field: 'assignment.zones'
  - field: 'create_time'
  - field: 'description'
  - field: 'etag'
  - field: 'guest_policy_id'
    provider_only: true
  - field: 'name'
  - field: 'package_repositories.apt.archive_type'
  - field: 'package_repositories.apt.components'
  - field: 'package_repositories.apt.distribution'
  - field: 'package_repositories.apt.gpg_key'
  - field: 'package_repositories.apt.uri'
  - field: 'package_repositories.goo.name'
  - field: 'package_repositories.goo.url'
  - field: 'package_repositories.yum.base_url'
  - field: 'package_repositories.yum.display_name'
  - field: 'package_repositories.yum.gpg_keys'
  - field: 'package_repositories.yum.id'
  - field: 'package_repositories.zypper.base_url'
  - field: 'package_repositories.zypper.display_name'
  - field: 'package_repositories.zypper.gpg_keys'
  - field: 'package_repositories.zypper.id'
  - field: 'packages.desired_state'
  - field: 'packages.manager'
  - field: 'packages.name'
  - field: 'recipes.artifacts.allow_insecure'
  - field: 'recipes.artifacts.gcs.bucket'
  - field: 'recipes.artifacts.gcs.generation'
  - field: 'recipes.artifacts.gcs.object'
  - field: 'recipes.artifacts.id'
  - field: 'recipes.artifacts.remote.check_sum'
  - field: 'recipes.artifacts.remote.uri'
  - field: 'recipes.desired_state'
  - field: 'recipes.install_steps.archive_extraction.artifact_id'
  - field: 'recipes.install_steps.archive_extraction.destination'
  - field: 'recipes.install_steps.archive_extraction.type'
  - field: 'recipes.install_steps.dpkg_installation.artifact_id'
  - field: 'recipes.install_steps.file_copy.artifact_id'
  - field: 'recipes.install_steps.file_copy.destination'
  - field: 'recipes.install_steps.file_copy.overwrite'
  - field: 'recipes.install_steps.file_copy.permissions'
  - field: 'recipes.install_steps.file_exec.allowed_exit_codes'
  - field: 'recipes.install_steps.file_exec.args'
  - field: 'recipes.install_steps.file_exec.artifact_id'
  - field: 'recipes.install_steps.file_exec.local_path'
  - field: 'recipes.install_steps.msi_installation.allowed_exit_codes'
  - field: 'recipes.install_steps.msi_installation.artifact_id'
  - field: 'recipes.install_steps.msi_installation.flags'
  - field: 'recipes.install_steps.rpm_installation.artifact_id'
  - field: 'recipes.install_steps.script_run.allowed_exit_codes'
  - field: 'recipes.install_steps.script_run.interpreter'
  - field: 'recipes.install_steps.script_run.script'
  - field: 'recipes.name'
  - field: 'recipes.update_steps.archive_extraction.artifact_id'
  - field: 'recipes.update_steps.archive_extraction.destination'
  - field: 'recipes.update_steps.archive_extraction.type'
  - field: 'recipes.update_steps.dpkg_installation.artifact_id'
  - field: 'recipes.update_steps.file_copy.artifact_id'
  - field: 'recipes.update_steps.file_copy.destination'
  - field: 'recipes.update_steps.file_copy.overwrite'
  - field: 'recipes.update_steps.file_copy.permissions'
  - field: 'recipes.update_steps.file_exec.allowed_exit_codes'
  - field: 'recipes.update_steps.file_exec.args'
  - field: 'recipes.update_steps.file_exec.artifact_id'
  - field: 'recipes.update_steps.file_exec.local_path'
  - field: 'recipes.update_steps.msi_installation.allowed_exit_codes'
  - field: 'recipes.update_steps.msi_installation.artifact_id'
  - field: 'recipes.update_steps.msi_installation.flags'
  - field: 'recipes.update_steps.rpm_installation.artifact_id'
  - field: 'recipes.update_steps.script_run.allowed_exit_codes'
  - field: 'recipes.update_steps.script_run.interpreter'
  - field: 'recipes.update_steps.script_run.script'
  - field: 'recipes.version'
  - field: 'update_time'
