// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/vertexai/FeatureOnlineStoreFeatureview.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/examples/base_configs/iam_test_file.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package vertexai_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
)

var (
	_ = fmt.Sprintf
	_ = strings.Trim
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
)

func TestAccVertexAIFeatureOnlineStoreFeatureviewIamBindingGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccVertexAIFeatureOnlineStoreFeatureviewIamBinding_basicGenerated(context),
			},
			{
				ResourceName:      "google_vertex_ai_feature_online_store_featureview_iam_binding.foo",
				ImportStateIdFunc: generateVertexAIFeatureOnlineStoreFeatureviewIAMBindingStateID("google_vertex_ai_feature_online_store_featureview_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				// Test Iam Binding update
				Config: testAccVertexAIFeatureOnlineStoreFeatureviewIamBinding_updateGenerated(context),
			},
			{
				ResourceName:      "google_vertex_ai_feature_online_store_featureview_iam_binding.foo",
				ImportStateIdFunc: generateVertexAIFeatureOnlineStoreFeatureviewIAMBindingStateID("google_vertex_ai_feature_online_store_featureview_iam_binding.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccVertexAIFeatureOnlineStoreFeatureviewIamMemberGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				// Test Iam Member creation (no update for member, no need to test)
				Config: testAccVertexAIFeatureOnlineStoreFeatureviewIamMember_basicGenerated(context),
			},
			{
				ResourceName:      "google_vertex_ai_feature_online_store_featureview_iam_member.foo",
				ImportStateIdFunc: generateVertexAIFeatureOnlineStoreFeatureviewIAMMemberStateID("google_vertex_ai_feature_online_store_featureview_iam_member.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func TestAccVertexAIFeatureOnlineStoreFeatureviewIamPolicyGenerated(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"random_suffix": acctest.RandString(t, 10),
		"role":          "roles/viewer",
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderFactories(t),
		Steps: []resource.TestStep{
			{
				Config: testAccVertexAIFeatureOnlineStoreFeatureviewIamPolicy_basicGenerated(context),
				Check:  resource.TestCheckResourceAttrSet("data.google_vertex_ai_feature_online_store_featureview_iam_policy.foo", "policy_data"),
			},
			{
				ResourceName:      "google_vertex_ai_feature_online_store_featureview_iam_policy.foo",
				ImportStateIdFunc: generateVertexAIFeatureOnlineStoreFeatureviewIAMPolicyStateID("google_vertex_ai_feature_online_store_featureview_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
			{
				Config: testAccVertexAIFeatureOnlineStoreFeatureviewIamPolicy_emptyBinding(context),
			},
			{
				ResourceName:      "google_vertex_ai_feature_online_store_featureview_iam_policy.foo",
				ImportStateIdFunc: generateVertexAIFeatureOnlineStoreFeatureviewIAMPolicyStateID("google_vertex_ai_feature_online_store_featureview_iam_policy.foo"),
				ImportState:       true,
				ImportStateVerify: true,
			},
		},
	})
}

func testAccVertexAIFeatureOnlineStoreFeatureviewIamMember_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_vertex_ai_feature_online_store" "featureonlinestore" {
  name = "tf_test_example_feature_view%{random_suffix}"
  labels = {
    foo = "bar"
  }
  region = "us-central1"
  bigtable {
    auto_scaling {
      min_node_count         = 1
      max_node_count         = 2
      cpu_utilization_target = 80
    }
  }
}

resource "google_bigquery_dataset" "tf-test-dataset" {

  dataset_id    = "tf_test_example_feature_view%{random_suffix}"
  friendly_name = "test"
  description   = "This is a test description"
  location      = "US"
}

resource "google_bigquery_table" "tf-test-table" {
  deletion_protection = false

  dataset_id = google_bigquery_dataset.tf-test-dataset.dataset_id
  table_id   = "tf_test_example_feature_view%{random_suffix}"
  schema     = <<EOF
  [
  {
    "name": "entity_id",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "Test default entity_id"
  },
    {
    "name": "test_entity_column",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "test secondary entity column"
  },
  {
    "name": "feature_timestamp",
    "mode": "NULLABLE",
    "type": "TIMESTAMP",
    "description": "Default timestamp value"
  }
]
EOF
}

resource "google_vertex_ai_feature_online_store_featureview" "featureview" {
  name                 = "tf_test_example_feature_view%{random_suffix}"
  region               = "us-central1"
  feature_online_store = google_vertex_ai_feature_online_store.featureonlinestore.name
  sync_config {
    cron = "0 0 * * *"
  }
  big_query_source {
    uri               = "bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}"
    entity_id_columns = ["test_entity_column"]

  }
}

data "google_project" "project" {
  provider = google
}

resource "google_vertex_ai_feature_online_store_featureview_iam_member" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  role = "%{role}"
  member = "user:admin@hashicorptest.com"
}
`, context)
}

func testAccVertexAIFeatureOnlineStoreFeatureviewIamPolicy_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_vertex_ai_feature_online_store" "featureonlinestore" {
  name = "tf_test_example_feature_view%{random_suffix}"
  labels = {
    foo = "bar"
  }
  region = "us-central1"
  bigtable {
    auto_scaling {
      min_node_count         = 1
      max_node_count         = 2
      cpu_utilization_target = 80
    }
  }
}

resource "google_bigquery_dataset" "tf-test-dataset" {

  dataset_id    = "tf_test_example_feature_view%{random_suffix}"
  friendly_name = "test"
  description   = "This is a test description"
  location      = "US"
}

resource "google_bigquery_table" "tf-test-table" {
  deletion_protection = false

  dataset_id = google_bigquery_dataset.tf-test-dataset.dataset_id
  table_id   = "tf_test_example_feature_view%{random_suffix}"
  schema     = <<EOF
  [
  {
    "name": "entity_id",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "Test default entity_id"
  },
    {
    "name": "test_entity_column",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "test secondary entity column"
  },
  {
    "name": "feature_timestamp",
    "mode": "NULLABLE",
    "type": "TIMESTAMP",
    "description": "Default timestamp value"
  }
]
EOF
}

resource "google_vertex_ai_feature_online_store_featureview" "featureview" {
  name                 = "tf_test_example_feature_view%{random_suffix}"
  region               = "us-central1"
  feature_online_store = google_vertex_ai_feature_online_store.featureonlinestore.name
  sync_config {
    cron = "0 0 * * *"
  }
  big_query_source {
    uri               = "bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}"
    entity_id_columns = ["test_entity_column"]

  }
}

data "google_project" "project" {
  provider = google
}

data "google_iam_policy" "foo" {
  binding {
    role = "%{role}"
    members = ["user:admin@hashicorptest.com"]
  }
}

resource "google_vertex_ai_feature_online_store_featureview_iam_policy" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  policy_data = data.google_iam_policy.foo.policy_data
}

data "google_vertex_ai_feature_online_store_featureview_iam_policy" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  depends_on = [
    google_vertex_ai_feature_online_store_featureview_iam_policy.foo
  ]
}
`, context)
}

func testAccVertexAIFeatureOnlineStoreFeatureviewIamPolicy_emptyBinding(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_vertex_ai_feature_online_store" "featureonlinestore" {
  name = "tf_test_example_feature_view%{random_suffix}"
  labels = {
    foo = "bar"
  }
  region = "us-central1"
  bigtable {
    auto_scaling {
      min_node_count         = 1
      max_node_count         = 2
      cpu_utilization_target = 80
    }
  }
}

resource "google_bigquery_dataset" "tf-test-dataset" {

  dataset_id    = "tf_test_example_feature_view%{random_suffix}"
  friendly_name = "test"
  description   = "This is a test description"
  location      = "US"
}

resource "google_bigquery_table" "tf-test-table" {
  deletion_protection = false

  dataset_id = google_bigquery_dataset.tf-test-dataset.dataset_id
  table_id   = "tf_test_example_feature_view%{random_suffix}"
  schema     = <<EOF
  [
  {
    "name": "entity_id",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "Test default entity_id"
  },
    {
    "name": "test_entity_column",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "test secondary entity column"
  },
  {
    "name": "feature_timestamp",
    "mode": "NULLABLE",
    "type": "TIMESTAMP",
    "description": "Default timestamp value"
  }
]
EOF
}

resource "google_vertex_ai_feature_online_store_featureview" "featureview" {
  name                 = "tf_test_example_feature_view%{random_suffix}"
  region               = "us-central1"
  feature_online_store = google_vertex_ai_feature_online_store.featureonlinestore.name
  sync_config {
    cron = "0 0 * * *"
  }
  big_query_source {
    uri               = "bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}"
    entity_id_columns = ["test_entity_column"]

  }
}

data "google_project" "project" {
  provider = google
}

data "google_iam_policy" "foo" {
}

resource "google_vertex_ai_feature_online_store_featureview_iam_policy" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  policy_data = data.google_iam_policy.foo.policy_data
}
`, context)
}

func testAccVertexAIFeatureOnlineStoreFeatureviewIamBinding_basicGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_vertex_ai_feature_online_store" "featureonlinestore" {
  name = "tf_test_example_feature_view%{random_suffix}"
  labels = {
    foo = "bar"
  }
  region = "us-central1"
  bigtable {
    auto_scaling {
      min_node_count         = 1
      max_node_count         = 2
      cpu_utilization_target = 80
    }
  }
}

resource "google_bigquery_dataset" "tf-test-dataset" {

  dataset_id    = "tf_test_example_feature_view%{random_suffix}"
  friendly_name = "test"
  description   = "This is a test description"
  location      = "US"
}

resource "google_bigquery_table" "tf-test-table" {
  deletion_protection = false

  dataset_id = google_bigquery_dataset.tf-test-dataset.dataset_id
  table_id   = "tf_test_example_feature_view%{random_suffix}"
  schema     = <<EOF
  [
  {
    "name": "entity_id",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "Test default entity_id"
  },
    {
    "name": "test_entity_column",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "test secondary entity column"
  },
  {
    "name": "feature_timestamp",
    "mode": "NULLABLE",
    "type": "TIMESTAMP",
    "description": "Default timestamp value"
  }
]
EOF
}

resource "google_vertex_ai_feature_online_store_featureview" "featureview" {
  name                 = "tf_test_example_feature_view%{random_suffix}"
  region               = "us-central1"
  feature_online_store = google_vertex_ai_feature_online_store.featureonlinestore.name
  sync_config {
    cron = "0 0 * * *"
  }
  big_query_source {
    uri               = "bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}"
    entity_id_columns = ["test_entity_column"]

  }
}

data "google_project" "project" {
  provider = google
}

resource "google_vertex_ai_feature_online_store_featureview_iam_binding" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com"]
}
`, context)
}

func testAccVertexAIFeatureOnlineStoreFeatureviewIamBinding_updateGenerated(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_vertex_ai_feature_online_store" "featureonlinestore" {
  name = "tf_test_example_feature_view%{random_suffix}"
  labels = {
    foo = "bar"
  }
  region = "us-central1"
  bigtable {
    auto_scaling {
      min_node_count         = 1
      max_node_count         = 2
      cpu_utilization_target = 80
    }
  }
}

resource "google_bigquery_dataset" "tf-test-dataset" {

  dataset_id    = "tf_test_example_feature_view%{random_suffix}"
  friendly_name = "test"
  description   = "This is a test description"
  location      = "US"
}

resource "google_bigquery_table" "tf-test-table" {
  deletion_protection = false

  dataset_id = google_bigquery_dataset.tf-test-dataset.dataset_id
  table_id   = "tf_test_example_feature_view%{random_suffix}"
  schema     = <<EOF
  [
  {
    "name": "entity_id",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "Test default entity_id"
  },
    {
    "name": "test_entity_column",
    "mode": "NULLABLE",
    "type": "STRING",
    "description": "test secondary entity column"
  },
  {
    "name": "feature_timestamp",
    "mode": "NULLABLE",
    "type": "TIMESTAMP",
    "description": "Default timestamp value"
  }
]
EOF
}

resource "google_vertex_ai_feature_online_store_featureview" "featureview" {
  name                 = "tf_test_example_feature_view%{random_suffix}"
  region               = "us-central1"
  feature_online_store = google_vertex_ai_feature_online_store.featureonlinestore.name
  sync_config {
    cron = "0 0 * * *"
  }
  big_query_source {
    uri               = "bq://${google_bigquery_table.tf-test-table.project}.${google_bigquery_table.tf-test-table.dataset_id}.${google_bigquery_table.tf-test-table.table_id}"
    entity_id_columns = ["test_entity_column"]

  }
}

data "google_project" "project" {
  provider = google
}

resource "google_vertex_ai_feature_online_store_featureview_iam_binding" "foo" {
  region = google_vertex_ai_feature_online_store_featureview.featureview.region
  feature_online_store = google_vertex_ai_feature_online_store_featureview.featureview.feature_online_store
  feature_view = google_vertex_ai_feature_online_store_featureview.featureview.name
  role = "%{role}"
  members = ["user:admin@hashicorptest.com", "user:gterraformtest1@gmail.com"]
}
`, context)
}

func generateVertexAIFeatureOnlineStoreFeatureviewIAMPolicyStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		feature_online_store := tpgresource.GetResourceNameFromSelfLink(rawState["feature_online_store"])
		feature_view := tpgresource.GetResourceNameFromSelfLink(rawState["feature_view"])
		return acctest.BuildIAMImportId(fmt.Sprintf("%s/featureViews/%s", feature_online_store, feature_view), "", "", rawState["condition.0.title"]), nil
	}
}

func generateVertexAIFeatureOnlineStoreFeatureviewIAMBindingStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		feature_online_store := tpgresource.GetResourceNameFromSelfLink(rawState["feature_online_store"])
		feature_view := tpgresource.GetResourceNameFromSelfLink(rawState["feature_view"])
		return acctest.BuildIAMImportId(fmt.Sprintf("%s/featureViews/%s", feature_online_store, feature_view), rawState["role"], "", rawState["condition.0.title"]), nil
	}
}

func generateVertexAIFeatureOnlineStoreFeatureviewIAMMemberStateID(iamResourceAddr string) func(*terraform.State) (string, error) {
	return func(state *terraform.State) (string, error) {
		var rawState map[string]string
		for _, m := range state.Modules {
			if len(m.Resources) > 0 {
				if v, ok := m.Resources[iamResourceAddr]; ok {
					rawState = v.Primary.Attributes
				}
			}
		}
		fmt.Printf("raw state %s\n", rawState)
		feature_online_store := tpgresource.GetResourceNameFromSelfLink(rawState["feature_online_store"])
		feature_view := tpgresource.GetResourceNameFromSelfLink(rawState["feature_view"])
		return acctest.BuildIAMImportId(fmt.Sprintf("%s/featureViews/%s", feature_online_store, feature_view), rawState["role"], rawState["member"], rawState["condition.0.title"]), nil
	}
}
