// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/vertexai/FeaturestoreEntitytype.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/iam_policy.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package vertexai

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"google.golang.org/api/cloudresourcemanager/v1"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgiamresource"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

var (
	_ = regexp.Match
	_ = strings.Trim
	_ = errwrap.Wrap
	_ = schema.Noop
)

func init() {
	registry.Schema{
		Name:        "google_vertex_ai_featurestore_entitytype_iam_binding",
		ProductName: "VertexAI",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      tpgiamresource.ResourceIamBinding(VertexAIFeaturestoreEntitytypeIamSchema, VertexAIFeaturestoreEntitytypeIamUpdaterProducer, VertexAIFeaturestoreEntitytypeIdParseFunc),
	}.Register()
	registry.Schema{
		Name:        "google_vertex_ai_featurestore_entitytype_iam_member",
		ProductName: "VertexAI",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      tpgiamresource.ResourceIamMember(VertexAIFeaturestoreEntitytypeIamSchema, VertexAIFeaturestoreEntitytypeIamUpdaterProducer, VertexAIFeaturestoreEntitytypeIdParseFunc),
	}.Register()
	registry.Schema{
		Name:        "google_vertex_ai_featurestore_entitytype_iam_policy",
		ProductName: "VertexAI",
		Type:        registry.SchemaTypeIAMResource,
		Schema:      tpgiamresource.ResourceIamPolicy(VertexAIFeaturestoreEntitytypeIamSchema, VertexAIFeaturestoreEntitytypeIamUpdaterProducer, VertexAIFeaturestoreEntitytypeIdParseFunc),
	}.Register()
	registry.Schema{
		Name:        "google_vertex_ai_featurestore_entitytype_iam_policy",
		ProductName: "VertexAI",
		Type:        registry.SchemaTypeIAMDataSource,
		Schema:      tpgiamresource.DataSourceIamPolicy(VertexAIFeaturestoreEntitytypeIamSchema, VertexAIFeaturestoreEntitytypeIamUpdaterProducer),
	}.Register()
}

var VertexAIFeaturestoreEntitytypeIamSchema = map[string]*schema.Schema{
	"featurestore": {
		Type:     schema.TypeString,
		Required: true,
		ForceNew: true,
	},
	"entitytype": {
		Type:             schema.TypeString,
		Required:         true,
		ForceNew:         true,
		DiffSuppressFunc: tpgresource.CompareSelfLinkOrResourceName,
	},
}

type VertexAIFeaturestoreEntitytypeIamUpdater struct {
	featurestore string
	entitytype   string
	d            tpgresource.TerraformResourceData
	Config       *transport_tpg.Config
}

func VertexAIFeaturestoreEntitytypeIamUpdaterProducer(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (tpgiamresource.ResourceIamUpdater, error) {
	values := make(map[string]string)

	if v, ok := d.GetOk("featurestore"); ok {
		values["featurestore"] = v.(string)
	}

	if v, ok := d.GetOk("entitytype"); ok {
		values["entitytype"] = v.(string)
	}

	// We may have gotten either a long or short name, so attempt to parse long name if possible
	m, err := tpgresource.GetImportIdQualifiers([]string{"(?P<featurestore>.+)/entityTypes/(?P<entitytype>[^/]+)", "(?P<entitytype>[^/]+)"}, d, config, d.Get("entitytype").(string))
	if err != nil {
		return nil, err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &VertexAIFeaturestoreEntitytypeIamUpdater{
		featurestore: values["featurestore"],
		entitytype:   values["entitytype"],
		d:            d,
		Config:       config,
	}

	if err := d.Set("featurestore", u.featurestore); err != nil {
		return nil, fmt.Errorf("Error setting featurestore: %s", err)
	}
	if err := d.Set("entitytype", u.GetResourceId()); err != nil {
		return nil, fmt.Errorf("Error setting entitytype: %s", err)
	}

	return u, nil
}

func VertexAIFeaturestoreEntitytypeIdParseFunc(d *schema.ResourceData, config *transport_tpg.Config) error {
	values := make(map[string]string)

	m, err := tpgresource.GetImportIdQualifiers([]string{"(?P<featurestore>.+)/entityTypes/(?P<entitytype>[^/]+)", "(?P<entitytype>[^/]+)"}, d, config, d.Id())
	if err != nil {
		return err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &VertexAIFeaturestoreEntitytypeIamUpdater{
		featurestore: values["featurestore"],
		entitytype:   values["entitytype"],
		d:            d,
		Config:       config,
	}
	if err := d.Set("entitytype", u.GetResourceId()); err != nil {
		return fmt.Errorf("Error setting entitytype: %s", err)
	}
	d.SetId(u.GetResourceId())
	return nil
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) GetResourceIamPolicy() (*cloudresourcemanager.Policy, error) {
	url, err := u.qualifyFeaturestoreEntitytypeUrl("getIamPolicy")
	if err != nil {
		return nil, err
	}

	var obj map[string]interface{}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return nil, err
	}

	policy, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "POST",
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
	})
	if err != nil {
		return nil, fmt.Errorf("Error retrieving IAM policy for %s: %w", u.DescribeResource(), err)
	}

	out := &cloudresourcemanager.Policy{}
	err = tpgresource.Convert(policy, out)
	if err != nil {
		return nil, fmt.Errorf("Cannot convert a policy to a resource manager policy: %w", err)
	}

	return out, nil
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) SetResourceIamPolicy(policy *cloudresourcemanager.Policy) error {
	json, err := tpgresource.ConvertToMap(policy)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	obj["policy"] = json

	url, err := u.qualifyFeaturestoreEntitytypeUrl("setIamPolicy")
	if err != nil {
		return err
	}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return err
	}

	_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "POST",
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   u.d.Timeout(schema.TimeoutCreate),
	})
	if err != nil {
		return fmt.Errorf("Error setting IAM policy for %s: %w", u.DescribeResource(), err)
	}

	return nil
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) qualifyFeaturestoreEntitytypeUrl(methodIdentifier string) (string, error) {
	urlTemplate := fmt.Sprintf("{{VertexAIBasePath}}%s:%s", fmt.Sprintf("%s/entityTypes/%s", u.featurestore, u.entitytype), methodIdentifier)
	url, err := tpgresource.ReplaceVars(u.d, u.Config, urlTemplate)
	if err != nil {
		return "", err
	}
	return url, nil
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) GetResourceId() string {
	return fmt.Sprintf("%s/entityTypes/%s", u.featurestore, u.entitytype)
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) GetMutexKey() string {
	return fmt.Sprintf("iam-vertexai-featurestoreentitytype-%s", u.GetResourceId())
}

func (u *VertexAIFeaturestoreEntitytypeIamUpdater) DescribeResource() string {
	return fmt.Sprintf("vertexai featurestoreentitytype %q", u.GetResourceId())
}
