// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This code is generated by Magic Modules using the following:
//
//     Configuration: https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/products/vertexai/FeatureOnlineStoreFeatureview.yaml
//     Template:      https://github.com/GoogleCloudPlatform/magic-modules/tree/main/mmv1/templates/terraform/iam_policy.go.tmpl
//
//     DO NOT EDIT this file directly. Any changes made to this file will be
//     overwritten during the next generation cycle.
//
// ----------------------------------------------------------------------------

package vertexai

import (
	"fmt"
	"regexp"
	"strings"

	"github.com/hashicorp/errwrap"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"google.golang.org/api/cloudresourcemanager/v1"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgiamresource"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

var (
	_ = regexp.Match
	_ = strings.Trim
	_ = errwrap.Wrap
	_ = schema.Noop
)

var VertexAIFeatureOnlineStoreFeatureviewIamSchema = map[string]*schema.Schema{
	"project": {
		Type:     schema.TypeString,
		Computed: true,
		Optional: true,
		ForceNew: true,
	},
	"region": {
		Type:     schema.TypeString,
		Computed: true,
		Optional: true,
		ForceNew: true,
	},
	"feature_online_store": {
		Type:     schema.TypeString,
		Required: true,
		ForceNew: true,
	},
	"feature_view": {
		Type:             schema.TypeString,
		Required:         true,
		ForceNew:         true,
		DiffSuppressFunc: tpgresource.CompareSelfLinkOrResourceName,
	},
}

type VertexAIFeatureOnlineStoreFeatureviewIamUpdater struct {
	project            string
	region             string
	featureOnlineStore string
	featureView        string
	d                  tpgresource.TerraformResourceData
	Config             *transport_tpg.Config
}

func VertexAIFeatureOnlineStoreFeatureviewIamUpdaterProducer(d tpgresource.TerraformResourceData, config *transport_tpg.Config) (tpgiamresource.ResourceIamUpdater, error) {
	values := make(map[string]string)

	project, _ := tpgresource.GetProject(d, config)
	if project != "" {
		if err := d.Set("project", project); err != nil {
			return nil, fmt.Errorf("Error setting project: %s", err)
		}
	}
	values["project"] = project
	region, _ := tpgresource.GetRegion(d, config)
	if region != "" {
		if err := d.Set("region", region); err != nil {
			return nil, fmt.Errorf("Error setting region: %s", err)
		}
	}
	values["region"] = region
	if v, ok := d.GetOk("feature_online_store"); ok {
		values["feature_online_store"] = v.(string)
	}

	if v, ok := d.GetOk("feature_view"); ok {
		values["feature_view"] = v.(string)
	}

	// We may have gotten either a long or short name, so attempt to parse long name if possible
	m, err := tpgresource.GetImportIdQualifiers([]string{"(?P<feature_online_store>[^/]+)/featureViews/(?P<feature_view>[^/]+)", "(?P<feature_online_store>[^/]+)/(?P<feature_view>[^/]+)", "(?P<feature_view>[^/]+)"}, d, config, d.Get("feature_view").(string))
	if err != nil {
		return nil, err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &VertexAIFeatureOnlineStoreFeatureviewIamUpdater{
		project:            values["project"],
		region:             values["region"],
		featureOnlineStore: values["feature_online_store"],
		featureView:        values["feature_view"],
		d:                  d,
		Config:             config,
	}

	if err := d.Set("project", u.project); err != nil {
		return nil, fmt.Errorf("Error setting project: %s", err)
	}
	if err := d.Set("region", u.region); err != nil {
		return nil, fmt.Errorf("Error setting region: %s", err)
	}
	if err := d.Set("feature_online_store", u.featureOnlineStore); err != nil {
		return nil, fmt.Errorf("Error setting feature_online_store: %s", err)
	}
	if err := d.Set("feature_view", u.GetResourceId()); err != nil {
		return nil, fmt.Errorf("Error setting feature_view: %s", err)
	}

	return u, nil
}

func VertexAIFeatureOnlineStoreFeatureviewIdParseFunc(d *schema.ResourceData, config *transport_tpg.Config) error {
	values := make(map[string]string)

	project, _ := tpgresource.GetProject(d, config)
	if project != "" {
		values["project"] = project
	}

	region, _ := tpgresource.GetRegion(d, config)
	if region != "" {
		values["region"] = region
	}

	m, err := tpgresource.GetImportIdQualifiers([]string{"(?P<feature_online_store>[^/]+)/featureViews/(?P<feature_view>[^/]+)", "(?P<feature_online_store>[^/]+)/(?P<feature_view>[^/]+)", "(?P<feature_view>[^/]+)"}, d, config, d.Id())
	if err != nil {
		return err
	}

	for k, v := range m {
		values[k] = v
	}

	u := &VertexAIFeatureOnlineStoreFeatureviewIamUpdater{
		project:            values["project"],
		region:             values["region"],
		featureOnlineStore: values["feature_online_store"],
		featureView:        values["feature_view"],
		d:                  d,
		Config:             config,
	}
	if err := d.Set("feature_view", u.GetResourceId()); err != nil {
		return fmt.Errorf("Error setting feature_view: %s", err)
	}
	d.SetId(u.GetResourceId())
	return nil
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) GetResourceIamPolicy() (*cloudresourcemanager.Policy, error) {
	url, err := u.qualifyFeatureOnlineStoreFeatureviewUrl("getIamPolicy")
	if err != nil {
		return nil, err
	}

	project, err := tpgresource.GetProject(u.d, u.Config)
	if err != nil {
		return nil, err
	}
	var obj map[string]interface{}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return nil, err
	}

	policy, err := transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "POST",
		Project:   project,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
	})
	if err != nil {
		return nil, fmt.Errorf("Error retrieving IAM policy for %s: %w", u.DescribeResource(), err)
	}

	out := &cloudresourcemanager.Policy{}
	err = tpgresource.Convert(policy, out)
	if err != nil {
		return nil, fmt.Errorf("Cannot convert a policy to a resource manager policy: %w", err)
	}

	return out, nil
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) SetResourceIamPolicy(policy *cloudresourcemanager.Policy) error {
	json, err := tpgresource.ConvertToMap(policy)
	if err != nil {
		return err
	}

	obj := make(map[string]interface{})
	obj["policy"] = json

	url, err := u.qualifyFeatureOnlineStoreFeatureviewUrl("setIamPolicy")
	if err != nil {
		return err
	}
	project, err := tpgresource.GetProject(u.d, u.Config)
	if err != nil {
		return err
	}

	userAgent, err := tpgresource.GenerateUserAgentString(u.d, u.Config.UserAgent)
	if err != nil {
		return err
	}

	_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
		Config:    u.Config,
		Method:    "POST",
		Project:   project,
		RawURL:    url,
		UserAgent: userAgent,
		Body:      obj,
		Timeout:   u.d.Timeout(schema.TimeoutCreate),
	})
	if err != nil {
		return fmt.Errorf("Error setting IAM policy for %s: %w", u.DescribeResource(), err)
	}

	return nil
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) qualifyFeatureOnlineStoreFeatureviewUrl(methodIdentifier string) (string, error) {
	urlTemplate := fmt.Sprintf("{{VertexAIBasePath}}%s:%s", fmt.Sprintf("projects/%s/locations/%s/featureOnlineStores/%s/featureViews/%s", u.project, u.region, u.featureOnlineStore, u.featureView), methodIdentifier)
	url, err := tpgresource.ReplaceVars(u.d, u.Config, urlTemplate)
	if err != nil {
		return "", err
	}
	return url, nil
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) GetResourceId() string {
	return fmt.Sprintf("projects/%s/locations/%s/featureOnlineStores/%s/featureViews/%s", u.project, u.region, u.featureOnlineStore, u.featureView)
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) GetMutexKey() string {
	return fmt.Sprintf("iam-vertexai-featureonlinestorefeatureview-%s", u.GetResourceId())
}

func (u *VertexAIFeatureOnlineStoreFeatureviewIamUpdater) DescribeResource() string {
	return fmt.Sprintf("vertexai featureonlinestorefeatureview %q", u.GetResourceId())
}
