// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google

import "github.com/hashicorp/terraform/helper/schema"

// If the base path has changed as a result of your PR, make sure to update
// the provider_reference page!
var CloudRunDefaultBasePath = "https://run.googleapis.com/v1alpha1/"
var CloudRunCustomEndpointEntryKey = "cloud_run_custom_endpoint"
var CloudRunCustomEndpointEntry = &schema.Schema{
	Type:         schema.TypeString,
	Optional:     true,
	ValidateFunc: validateCustomEndpoint,
	DefaultFunc: schema.MultiEnvDefaultFunc([]string{
		"GOOGLE_CLOUD_RUN_CUSTOM_ENDPOINT",
	}, CloudRunDefaultBasePath),
}

var GeneratedCloudRunResourcesMap = map[string]*schema.Resource{
	"google_cloud_run_domain_mapping": resourceCloudRunDomainMapping(),
	"google_cloud_run_service":        resourceCloudRunService(),
}
