// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package dataform_test

import (
	"fmt"
	"log"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"

	"google.golang.org/api/googleapi"
)

var (
	_ = fmt.Sprintf
	_ = log.Print
	_ = strconv.Atoi
	_ = strings.Trim
	_ = time.Now
	_ = resource.TestMain
	_ = terraform.NewState
	_ = envvar.TestEnvVar
	_ = tpgresource.SetLabels
	_ = transport_tpg.Config{}
	_ = googleapi.Error{}
)

func TestAccDataformConfig_dataformConfigWithKmsKeyExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"billing_account": envvar.GetTestBillingAccountFromEnv(t),
		"org_id":          envvar.GetTestOrgFromEnv(t),
		"random_suffix":   acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		ExternalProviders: map[string]resource.ExternalProvider{
			"time": {},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccDataformConfig_dataformConfigWithKmsKeyExample(context),
			},
			{
				ResourceName:            "google_dataform_config.config",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"region"},
			},
		},
	})
}

func testAccDataformConfig_dataformConfigWithKmsKeyExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_project" "project" {
  provider        = google-beta
  name            = "tf-test-project-1%{random_suffix}"
  project_id      = "tf-test-project-1%{random_suffix}"
  org_id          = "%{org_id}"
  billing_account = "%{billing_account}"
  deletion_policy = "DELETE"
}

# Enable Cloud Key KMS API
resource "google_project_service" "cloudkms_api" {
  provider = google-beta
  project  = google_project.project.project_id
  service  = "cloudkms.googleapis.com"
  disable_on_destroy = false
}

# Enable Dataform API
resource "google_project_service" "dataform_api" {
  provider           = google-beta
  project            = google_project.project.project_id
  service            = "dataform.googleapis.com"
  disable_on_destroy = false
}

# Add a sleep to wait for IAM propagation after API enablement
resource "time_sleep" "wait_for_dataform_api" {
  create_duration = "30s"
  depends_on      = [
    google_project_service.dataform_api
  ]
}

# Retrieve the Dataform service identity
resource "google_project_service_identity" "dataform_sa" {
  provider = google-beta
  project  = google_project.project.project_id
  service  = "dataform.googleapis.com"
}

resource "google_kms_key_ring" "keyring" {
  provider   = google-beta
  project    = google_project.project.project_id
  name       = "tf-test-example-key-ring%{random_suffix}"
  location   = "us-central1"
  depends_on = [
    google_project_service.cloudkms_api
  ]
}

resource "google_kms_crypto_key" "example_key" {
  provider = google-beta
  name     = "tf-test-example-crypto-key-name%{random_suffix}"
  key_ring = google_kms_key_ring.keyring.id
}

# Grant the Encrypter/Decrypter role to the Dataform service agent on the KMS key
resource "google_kms_crypto_key_iam_member" "crypto_key_binding" {
  provider      = google-beta
  crypto_key_id = google_kms_crypto_key.example_key.id
  role          = "roles/cloudkms.cryptoKeyEncrypterDecrypter"
  member        = google_project_service_identity.dataform_sa.member
}

# Config with KMS key provided
resource "google_dataform_config" "config" {
  provider             = google-beta
  region               = "us-central1"
  default_kms_key_name = google_kms_crypto_key.example_key.id
  project              = google_project.project.project_id

  # Ensure IAM binding is created before the Dataform Config
  depends_on = [
    google_kms_crypto_key_iam_member.crypto_key_binding,
    time_sleep.wait_for_dataform_api
  ]
}
`, context)
}

func TestAccDataformConfig_dataformConfigWithoutKmsKeyExample(t *testing.T) {
	t.Parallel()

	context := map[string]interface{}{
		"billing_account": envvar.GetTestBillingAccountFromEnv(t),
		"org_id":          envvar.GetTestOrgFromEnv(t),
		"random_suffix":   acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		ExternalProviders: map[string]resource.ExternalProvider{
			"time": {},
		},
		Steps: []resource.TestStep{
			{
				Config: testAccDataformConfig_dataformConfigWithoutKmsKeyExample(context),
			},
			{
				ResourceName:            "google_dataform_config.config",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"region"},
			},
		},
	})
}

func testAccDataformConfig_dataformConfigWithoutKmsKeyExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_project" "project" {
  provider        = google-beta
  name            = "tf-test-project-1%{random_suffix}"
  project_id      = "tf-test-project-1%{random_suffix}"
  org_id          = "%{org_id}"
  billing_account = "%{billing_account}"
  deletion_policy = "DELETE"
}

# Enable Dataform API
resource "google_project_service" "dataform_api" {
  provider           = google-beta
  project            = google_project.project.project_id
  service            = "dataform.googleapis.com"
  disable_on_destroy = false
}

# Add a sleep to wait for IAM propagation after API enablement
resource "time_sleep" "wait_for_dataform_api" {
  create_duration = "30s"
  depends_on      = [
    google_project_service.dataform_api
  ]
}

# Config without KMS key provided
resource "google_dataform_config" "config" {
  provider = google-beta
  region   = "us-central1"
  project  = google_project.project.project_id

  # Ensure IAM binding is created before the Dataform Config
  depends_on = [
    time_sleep.wait_for_dataform_api
  ]
}
`, context)
}
