// Copyright IBM Corp. 2014, 2026
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

// Package tpuv2 contains resources, datasources, etc. for the cloud tpu v2 service.
package tpuv2

import (
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/registry"
)

var Product = registry.Product{
	Name:                 "tpuv2",
	BaseUrl:              "https://tpu.googleapis.com/v2alpha1/",
	CustomEndpointField:  "tpu_v2_custom_endpoint",
	CustomEndpointEnvVar: "GOOGLE_TPU_V2_CUSTOM_ENDPOINT",
}

func init() {
	Product.Register()
}
