# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_runtimeconfig_variable'
generation_type: 'handwritten'
api_service_name: 'runtimeconfig.googleapis.com'
api_version: 'v1beta1'
api_resource_type_kind: 'Variable'
fields:
  - field: 'name'
  - field: 'parent'
  - field: 'project'
  - field: 'text'
  - field: 'update_time'
  - field: 'value'
