# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_runtimeconfig_config'
generation_type: 'handwritten'
api_service_name: 'runtimeconfig.googleapis.com'
api_version: 'v1beta1'
api_resource_type_kind: 'RuntimeConfig'
fields:
  - field: 'description'
  - field: 'name'
  - field: 'project'
