resource: 'google_network_management_organization_vpc_flow_logs_config'
generation_type: 'mmv1'
source_file: 'products/networkmanagement/OrganizationVpcFlowLogsConfig.yaml'
api_service_name: 'networkmanagement.googleapis.com'
api_version: 'v1beta1'
api_resource_type_kind: 'OrganizationVpcFlowLogsConfig'
fields:
  - field: 'aggregation_interval'
  - field: 'create_time'
  - field: 'cross_project_metadata'
  - field: 'description'
  - field: 'effective_labels'
    provider_only: true
  - field: 'filter_expr'
  - field: 'flow_sampling'
  - field: 'labels'
  - field: 'location'
    provider_only: true
  - field: 'metadata'
  - field: 'metadata_fields'
  - field: 'name'
  - field: 'organization'
    provider_only: true
  - field: 'state'
  - field: 'terraform_labels'
    provider_only: true
  - field: 'update_time'
  - field: 'vpc_flow_logs_config_id'
    provider_only: true
