# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

resource: 'google_security_scanner_scan_config'
generation_type: 'mmv1'
source_file: 'products/securityscanner/ScanConfig.yaml'
api_service_name: 'websecurityscanner.googleapis.com'
api_version: 'v1beta'
api_resource_type_kind: 'ScanConfig'
fields:
  - field: 'authentication.custom_account.login_url'
  - field: 'authentication.custom_account.password'
  - field: 'authentication.custom_account.username'
  - field: 'authentication.google_account.password'
  - field: 'authentication.google_account.username'
  - field: 'blacklist_patterns'
  - field: 'display_name'
  - field: 'export_to_security_command_center'
  - field: 'max_qps'
  - field: 'name'
  - field: 'schedule.interval_duration_days'
  - field: 'schedule.schedule_time'
  - field: 'starting_urls'
  - field: 'target_platforms'
  - field: 'user_agent'
