// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    Type: MMv1     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by Magic Modules and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package saasruntime_test

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
	"github.com/hashicorp/terraform-plugin-testing/terraform"

	"github.com/hashicorp/terraform-provider-google-beta/google-beta/acctest"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/envvar"
	"github.com/hashicorp/terraform-provider-google-beta/google-beta/tpgresource"
	transport_tpg "github.com/hashicorp/terraform-provider-google-beta/google-beta/transport"
)

func TestAccSaasRuntimeUnit_saasRuntimeUnitBasicExample(t *testing.T) {
	t.Parallel()
	acctest.BootstrapIamMembers(t, []acctest.IamMember{
		{
			Member: "serviceAccount:service-{project_number}@gcp-sa-saasservicemgmt.iam.gserviceaccount.com",
			Role:   "roles/saasservicemgmt.serviceAgent",
		},
	})

	context := map[string]interface{}{
		"project":       envvar.GetTestProjectFromEnv(),
		"random_suffix": acctest.RandString(t, 10),
	}

	acctest.VcrTest(t, resource.TestCase{
		PreCheck:                 func() { acctest.AccTestPreCheck(t) },
		ProtoV5ProviderFactories: acctest.ProtoV5ProviderBetaFactories(t),
		CheckDestroy:             testAccCheckSaasRuntimeUnitDestroyProducer(t),
		Steps: []resource.TestStep{
			{
				Config: testAccSaasRuntimeUnit_saasRuntimeUnitBasicExample(context),
			},
			{
				ResourceName:            "google_saas_runtime_unit.example",
				ImportState:             true,
				ImportStateVerify:       true,
				ImportStateVerifyIgnore: []string{"annotations", "labels", "location", "terraform_labels", "unit_id"},
			},
		},
	})
}

func testAccSaasRuntimeUnit_saasRuntimeUnitBasicExample(context map[string]interface{}) string {
	return acctest.Nprintf(`
resource "google_saas_runtime_saas" "example_saas_regional" {
  provider = google-beta
  saas_id  = "tf-test-example-saas%{random_suffix}"
  location = "us-central1"

  locations {
    name = "us-central1"
  }
}

resource "google_saas_runtime_unit_kind" "example_unit_kind" {
  provider = google-beta
  location = "us-central1"
  unit_kind_id = "tf-test-example-unitkind%{random_suffix}"
  saas = google_saas_runtime_saas.example_saas_regional.id
}

resource "google_saas_runtime_unit" "example" {
  provider = google-beta
  location = "us-central1"
  unit_id = "tf-test-example-unit%{random_suffix}"
  unit_kind = google_saas_runtime_unit_kind.example_unit_kind.id
  management_mode = "MANAGEMENT_MODE_USER"
}
`, context)
}

func testAccCheckSaasRuntimeUnitDestroyProducer(t *testing.T) func(s *terraform.State) error {
	return func(s *terraform.State) error {
		for name, rs := range s.RootModule().Resources {
			if rs.Type != "google_saas_runtime_unit" {
				continue
			}
			if strings.HasPrefix(name, "data.") {
				continue
			}

			config := acctest.GoogleProviderConfig(t)

			url, err := tpgresource.ReplaceVarsForTest(config, rs, "{{SaasRuntimeBasePath}}projects/{{project}}/locations/{{location}}/units/{{unit_id}}")
			if err != nil {
				return err
			}

			billingProject := ""

			if config.BillingProject != "" {
				billingProject = config.BillingProject
			}

			_, err = transport_tpg.SendRequest(transport_tpg.SendRequestOptions{
				Config:    config,
				Method:    "GET",
				Project:   billingProject,
				RawURL:    url,
				UserAgent: config.UserAgent,
			})
			if err == nil {
				return fmt.Errorf("SaasRuntimeUnit still exists at %s", url)
			}
		}

		return nil
	}
}
