name: GoTest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Set up Go
      uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.31.0
      with:
        go-version-file: "go.mod"

    - name: Get dependencies
      run: |
        go mod download

    - name: Build and Lint
      run: make build

    - name: Test
      run: |
        make docscheck
        make testnolint