name: "Pull Request Reviewer"
on:
  pull_request_target:
    types: [opened, ready_for_review, reopened]

permissions:
  pull-requests: write

jobs:
  add-reviewer:
    if: ${{ github.actor != 'modular-magician' }}
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@f4648c0a9fdb753479e9e75fc251f507ce17bb7e # v2.0.0
        with:
          configuration-path: ".github/reviewer-lottery.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
